spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    driver-calss-name: org.h2.Driver
    username: sa
    jpa:
      show-sql: true
      hibernate:
        ddl-auto: create
    ouput:
      ansi:
        enabled: always
logging:
  level:
    org.hibernate.type: trace